### ISSUE TITLE
Parser Exception

### ISSUE THREAD

**Issue by dhivya29** [gturri/aXMLRPC#108]
After the last update we are getting parser exception issue 
as of now we are using  "com.github.gturri:aXMLRPC:master-SNAPSHOT "
How do we resolve?

**Comment by gturri** [comment]
The latest commits may have brought some regressions. Sorry about that. I've reverted them until I get the time to look at it more closely and come up with a better fix.
That being said, I have a few questions:

- has your issue been fixed? (I guess it may take some time until it's fixed, because I'm not sure what is generating the `master-SNAPSHOT` artifact and when it runs)
- could you give me more context on the error you had (ideally the stacktrace)? It would help me make sure I don't reintroduce this issue in the future
- why do you reference the version `master-SNAPSHOT` instead of a released one (the latest being `1.12.0`)? (using a released one would ensure you have deterministic build and run and would hence prevent such inconvenience)

Thanks in advance for your answers.

**Comment by dhivya29** [comment]
Ok Thanks for the update.will Check andet you know.

**Comment by dhivya29** [comment]
Can you please share the dependency

**Comment by gturri** [comment]
I'm not sure I understand which dependency you're talking about (in the sense that I've never released any `master-SNAPSHOT` artifact myself.

Could you use version `1.12.0` instead? Does it fix the issue you're experiencing?
