### ISSUE TITLE
After your last update facing this issue - de.timroes.axmlrpc.XMLRPCException: Error getting result from server." error in "onError

### ISSUE THREAD

**Issue by agilanbu** [gturri/aXMLRPC#109]
After your last update , am getting this "de.timroes.axmlrpc.XMLRPCException: Error getting result from server." error in "onError" block for every api call hit. 

my client is :
public OdooHelper(Context context, String meta_path) {
        try {
            this.generalUtils = GeneralUtils.getInstance();
            SessionManager sessionManager = new SessionManager(context);
            DBHelper db = DBHelper.getInstance(context);
            String mServer = String.format("https://.........", sessionManager.getData("db"));
            this.mUId = sessionManager.getUserId();
            this.mDb = sessionManager.getData("db");
            this.mPassword = sessionManager.getPassword();
            try {
                URL mUrl = new URL(mServer + "/xmlrpc/2/" + meta_path);
                client = new XMLRPCClient(mUrl);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

in gradle : 
 implementation 'com.github.gturri:aXMLRPC:master-SNAPSHOT'

and

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven { url 'https://maven.google.com' }
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }
}

**Comment by gturri** [comment]
The latest commits may have brought some regressions. Sorry about that. I've reverted them until I get the time to look at it more closely and come up with a better fix.
That being said, I have a few questions:

- has your issue been fixed? (I guess it may take some time until it's fixed, because I'm not sure what is generating the `master-SNAPSHOT` artifact and when it runs)
- could you give me more context on the error you had (ideally the stacktrace)? It would help me make sure I don't reintroduce this issue in the future
- why do you reference the version `master-SNAPSHOT` instead of a released one (the latest being `1.12.0`)? (using a released one would ensure you have deterministic build and run and would hence prevent such inconvenience)

Thanks in advance for your answers.

**Comment by agilanbu** [comment]
Thanks for the quick response, Still facing the same. Can you elaborate how can I use the 1.12.0 version in Android studio java.

**Comment by gturri** [comment]
I guess you have a `build.gradle` file somewhere in your project which contains something like this:

```
dependencies {
    implementation("fr.turri:aXMLRPC:master-SNAPSHOT")
}
```

try turning it into this:

```
dependencies {
    implementation("fr.turri:aXMLRPC:1.12.0")
}
```
