### ISSUE TITLE
Override Content-Type

### ISSUE THREAD

**Issue by scirocco-gt** [gturri/aXMLRPC#144]
The latest DokuWiki release 2024-02-06a “Kaos” responds to XMLRPC calls with “XML-RPC server accepts XML requests only.”

If the content-type is changed from "text/xml" to "application/xml", it works again.
-> https://www.dokuwiki.org/devel:xmlrpc:clients#sample_curl_client

But the content-type cannot be overwritten with "setCustomHttpHeader".

**Comment by gturri** [comment]
Thanks for this bug report.

According to the [xmlrpc specification](http://xmlrpc.com/spec.md) the correct content-type is `text/xml`. I will hence close this issue, and suggest that you open a bug report on Dokuwiki instead.
(that being said, if you want to create a pull request in order to make this header configurable, I'll have a look at it)

**Comment by scirocco-gt** [comment]
ok, thanks for your quick response!

**Comment by scirocco-gt** [comment]
There is already a [bug report](https://github.com/dokuwiki/dokuwiki/issues/4218). Thank you for your time!
