### ISSUE TITLE
Difference

### ISSUE THREAD

**Issue by meryaam** [gturri/aXMLRPC#52]
Hi 
I want just know the difference between aXMLRPC and XMLRPC because i want develop an android application interfacing with odoo(OpenErp) which one can i use

**Comment by gturri** [comment]
Hi @meryaam ,

xml-rpc is a protocol (see http://xmlrpc.scripting.com/spec.html) which is implemented by this library aXMLRPC.

odoo seems to have an xmlrpc interface (https://doc.odoo.com/6.0/developer/6_22_XML-RPC_web_services/), so you might be able to use this library.

However, you might want to use this fork https://github.com/gturri/aXMLRPC instead, because the development on this repository has been stopped (see https://github.com/timroes/aXMLRPC/issues/49).
(also, you should use 

Feel free to close this issue if it answer your question.

**Comment by skeppi** [comment]
@meryaam  were you able to connect and fetch from the database? bc i'm still stuck :'(

**Comment by gturri** [comment]
What code did you try? How does it fail?

**Comment by skeppi** [comment]
@gturri  Thanx for getting back to me I executed this code https://books.google.co.ma/books?id=CXriCgAAQBAJ&pg=PA40&lpg=PA40&dq=search+method+for+odoo+in+java&source=bl&ots=h5pExCSKXN&sig=9GU1VeFaAyDJtEtfMgDqoWu1SWk&hl=en&sa=X&redir_esc=y#v=onepage&q=search%20method%20for%20odoo%20in%20java&f=false turned out i was putting the permission thing inside the application rather than out now it works fine but I don't understand something like how can i return for example names of the partners because i saw the search read returns long could you help me :'(

**Comment by gturri** [comment]
No news from Meryaam for about a month, and skeppi found his answers on #26 => closing this issue
