### ISSUE TITLE
NullPointerException from call if null parameter in params array

### ISSUE THREAD

**Issue by kchvilyov** [gturri/aXMLRPC#53]
Thank you for useful library!
If I if use one null parameter in params array(fullParams) of the call request:
    result = client.call(method, fullParams);
I get Unprescribed exception:
java.lang.NullPointerException
    at de.timroes.axmlrpc.serializer.SerializerHandler.serialize(SerializerHandler.java:220)
    at de.timroes.axmlrpc.Call.getXMLParam(Call.java:82)
    at de.timroes.axmlrpc.Call.getXML(Call.java:64)
    at de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:653)
    at de.timroes.axmlrpc.XMLRPCClient.call(XMLRPCClient.java:455)
That is of object=null in this code:
            throw new XMLRPCException("No serializer found for type '"
                    + object.getClass().getName() + "'.");
It looks better: 
1. to send this null parameter.
2. return described by throws dXMLRPCException

**Comment by gturri** [comment]
Hi,

As far as I understand, you have a rather clear idea of how this behavior should be enhanced. What about submitting a pull request (along with a unit test)?

Also, I would be grateful if you could propose this pull request on the fork https://github.com/gturri/aXMLRPC, since it's there that development in being continued (see https://github.com/timroes/aXMLRPC/issues/49)

**Comment by adadion** [comment]
It happened to me just few days ago. And giving `FLAGS_NIL` did the trick!

`XMLRPCClient client = new XMLRPCClient(url, XMLRPCClient.FLAGS_NIL);`

**Comment by gturri** [comment]
Thanks for this information!
I'll close this issue then.

**Comment by agilanbu** [comment]
@adadion Thanks for your input. its worked for me.

**Comment by adadion** [comment]
> @adadion Thanks for your input. its worked for me.

You're welcome
