### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by EricHorvat** [gturri/aXMLRPC#58]
After I cloned the repository in my computer and include the code in my Android app, when I've tried to build the app, Android Studio throws that DateTimeSerializer needs fr.turri.jiso8601.Iso8601Deserializer. I looked for it in gturri gitHob account profile, cloned and include it. It works perfectly, but should advice in the readme or another place. Thanks!

**Comment by gturri** [comment]
Thank you for the bug report.

I'm not sure I understand: if you're using maven or gradle to build your project, doesn't it automatically download jiso8601 from maven central (http://search.maven.org/#search|ga|1|jiso8601)?

**Comment by EricHorvat** [comment]
Sorry for my delay!!
I downloaded the source code, not used maven nor gradle. And then, I copied and pasted in src folder. I only suggest to notify of this to other users than prefer to download the code.

**Comment by gturri** [comment]
Thanks for the explanation.

The information about this dependency is already available in the [pom.xml](https://github.com/gturri/aXMLRPC/blob/master/pom.xml#L40). It's a rather common file in the Java ecosystem, so I guess most users will know it.
I'd rather not duplicate this information, in particular because if I ever had a dependency, I'll have to update two places (well, in practice I'm sure I'll forget to update the README)
