### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lfr/turri/jiso8601/Iso8601Deserializer

### ISSUE THREAD

**Issue by cec91** [gturri/aXMLRPC#60]
I'm trying to make a normal xml rpc call but i get this error: 

java.lang.NoClassDefFoundError: Failed resolution of: Lfr/turri/jiso8601/Iso8601Deserializer

Does anyone know how to solve it? 
Thanks

**Comment by gturri** [comment]
It's probably because you're missing the dependency [jISO8601](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jISO8601%22)
It's a direct dependency of aXMLRPC as we can see in the [pom.xml](https://github.com/gturri/aXMLRPC/blob/master/pom.xml#L42) (actually it's the only needed dependency: the other are required for the tests)

I don't know how you built your project, but if you use maven or gradle, everything should go smoothly.

**Comment by cec91** [comment]
I took the jar file from [http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22fr.turri%22%20AND%20a%3A%22aXMLRPC%22](maven central)

is there a way to include that dependency ? 
Thanks!

**Comment by cec91** [comment]
sorry i did not see your link! i think it's enough download that jar! i ll let you know 
thanks

**Comment by cec91** [comment]
Thank you now it's working
