### ISSUE TITLE
ecvfrom failed: ECONNRESET (Connection reset by peer

### ISSUE THREAD

**Issue by ruswendra** [gturri/aXMLRPC#70]
Hi

I have a problem when develop android apps using xmlrpc to retrive data from odoo 9

I call method to search read like this :

    List conditions= Arrays.asList( Arrays.asList( Arrays.asList("id", ">=",3), Arrays.asList("id", "<=", 6)));

    Map fields = new HashMap() {{ put("fields", Arrays.asList( "date","salesperson_id","categ_id","product_id","price_total" )); }};

    long id = client.callAsync(listener, "execute_kw", db, Integer.parseInt(uid), password, object, "search_read", conditions, fields); return id

but I got exception like this  :

    "ecvfrom failed: ECONNRESET (Connection reset by peer"

Do you have an idea ? about this problem solution?

thanks

**Comment by gturri** [comment]
I've never heard of this error with aXMLRPC.
According to http://stackoverflow.com/q/1434451/1796345 it seems that the odoo server replied in an unexpected way.

To go further, you could:
* look at the logs on the odoo server (in particular to see if there are errors or warnings there)
* post the complete stack trace here

**Comment by ruswendra** [comment]
it's not happened when running on my real device, but i happenned when use genymotion emulator
maybe the problem on network setting emulator or anything on emulator

**Comment by gturri** [comment]
It's interesting to know that the behavior depends on the platform. Btw, do this failure happen every time on the emulator, or is it random?

Something that could be interesting could be to capture the traffic (with wireshark or tcpdump) that arrives on the server, in order to compare what is happening with the emulator and with the real device.

Also, I still believe it could be interesting to look at the log on the odoo server, and to have the complete stack trace
